### ISSUE TITLE
Package doesn't compile on Unity 2022.3 - "The name '_bufferLabel' does not exist"

### ISSUE THREAD

**Issue by ShacharWeis** [techno-dwarf-works/better-attributes#12]
I've imported this package on Unity 2022.3.29 and I get this error:

Library\PackageCache\com.tdw.better.commons@0.0.57\Editor\Drawers\SerializeReferenceField.cs(143,21): error CS0103: The name '_bufferLabel' does not exist in the current context
